file(GLOB_RECURSE XBASE_HEADERS "*.h")
file(GLOB_RECURSE XBASE_SOURCES "*.c")
add_library(xbase SHARED ${XBASE_SOURCES} ${XBASE_HEADERS})

if(XK_BUILD_TESTS)
  file(GLOB_RECURSE XBASE_TEST_SOURCES "*_test.cpp")
  add_executable(xbase_test ${XBASE_TEST_SOURCES})
  target_link_libraries(xbase_test PRIVATE xbase GTest::gtest GTest::gtest_main)
  add_test(NAME xbase_test COMMAND xbase_test)
endif()
